### PR TITLE
Simplify the Options portion of lrm-mapzen 

### PR DESCRIPTION
**Pull request by kdiluca**
-also some renaming

### CODE REVIEW

**Comment by kdiluca** [comment]
@hanbyul-here , is it possible to get this merged into your branch?

**Comment by hanbyul-here** [comment]
@kdiluca this change actually affects how to use lrm, and probably documentation needs to go along, so I wonder we should hold until we can offer compatible docs @rmglennon  ?

**Comment by hanbyul-here** [comment]
woops sorry, you were talking about `hanb/transit branch`, not `master` Never mind!!!

**Comment by hanbyul-here** [comment]
@kdiluca would you make example to run (it breaks now) ? then we can merge this.

**Comment by kdiluca** [comment]
@hanbyul-here I fixed the example and readme.  Please check it out!

**Comment by hanbyul-here** [comment]
Hey @kdiluca so I made tiny changes on top of your changes. I think it is good to have really basic example (costing auto without any options) so I changed index page of example to transit routing example with `transit.html` & `transit.js`, and index page of exampels has basic demo with `cosint:auto`. 

I also thought it can confuse users that waypoint is part of object when waypoints are actually passed separately, so I detached waypoints from demo obj.

**Comment by kdiluca** [comment]
@hanbyul-here makes sense & looks good! :+1:

**Pull request merged**
